version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "5050:5050"
    env_file:
      - .env
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5050
    environment:
      FLASK_DEBUG: 1
